<?php

/**
 * @file
 * Contains ipnotification.module..
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\ipnotification\Entity;
use Drupal\ipnotification\IpNotificationSendMail;


/**
 * Implements hook_help().
 */
function ipnotification_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ipnotification module.
    case 'help.page.ipnotification':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Notify administrators when users with specified IPs appear.') . '</p>';
      return $output;

    default:
 }
}

/**
 * Implements hook_entity_insert().
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function ipnotification_entity_insert(EntityInterface $entity) {
  $currentip = \Drupal::request()->getClientIp();
  $checker = new IpNotificationSendMail();
  $checker->ipCheckMailSend($currentip, $entity);
}

/**
 * Implements hook_user_login().
 *
 * @param $account
 *
 */
function ipnotification_user_login() {
  $checker = new IpNotificationSendMail();
  $checker->emailCheckMailSend();
}

/**
 * Implement hook_mail().
 *
 * @param $key
 * @param $message
 * @param $params
 */
function ipnotification_mail($key, &$message, $params) {

}

