<?php

/**
 * @file
 * Contains ipnotification.module..
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\ipnotification\IPnotificationsendmail;

/**
 * Implements hook_help().
 */
function ipnotification_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ipnotification module.
    case 'help.page.ipnotification':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Notify administrators when users with specified IPs appear.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_insert().
 */
function ipnotification_entity_insert(EntityInterface $entity) {
  $currentip = \Drupal::request()->getClientIp();
  $checker = new IPnotificationsendmail();
  /** @var \Drupal\ipnotification\Entity\IPnotification $ipnotification */
  $ids = \Drupal::entityQuery('ipnotification')->execute();
  $checker->ipCheckMailSend($currentip, $entity, $ids);
}

/**
 * Implements hook_user_login().
 */
function ipnotification_user_login() {
  $currentip = \Drupal::request()->getClientIp();
  $checker = new IPnotificationsendmail();
  /** @var \Drupal\ipnotification\Entity\IPnotification $ipnotification */
  $ids = \Drupal::entityQuery('ipnotification')->execute();
  $checker->emailCheckMailSend($currentip, $ids);
}

/**
 * Implements hook_mail().
 */
function ipnotification_mail($key, &$message, $params) {
  switch ($key) {
    case 'ipnotification':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = $params['subject'];
      $message['body'] = $params['message'];
      break;
  }
}
